sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js: '12'
install: yarn
dist: trusty
addons:
  sonarcloud:
    organization: erhangundogan
    token: ${SONAR_TOKEN}
script:
  - yarn build
  - yarn test -- --coverage --watchAll=false
  - sonar-scanner
